### ISSUE TITLE
The document needs update

### ISSUE THREAD

**Issue by haifengkao** [SwiftRex/BridgeMiddleware#5]
<img width="1083" alt="截圖 2022-02-23 上午3 04 50" src="https://user-images.githubusercontent.com/4080524/155201293-67605056-854d-4dc7-b1b1-b826e525f47c.png">

`--->` operator doesn't not exist

it has been changed to `>=>`

**Comment by luizmb** [comment]
https://github.com/SwiftRex/BridgeMiddleware/pull/7
